
name: Test and Build Kibana Notebooks

on: [pull_request, push]

env:
  PLUGIN_NAME: opendistroNotebooksKibana
  OD_VERSION: 1.13.2.0

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Kibana
        uses: actions/checkout@v1
        with:
          repository: elastic/kibana
          ref: v7.10.2
          path: kibana
      - name: Checkout Plugin
        uses: actions/checkout@v1
        with:
          path: kibana/plugins/kibana-notebooks
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '10.23.1'
      - name: Kibana Pluign Bootstrap
        run: |
          yarn kbn bootstrap
      - name: Build Artifact
        run: |
          yarn build
          mv ./build/*.zip ./build/${{ env.PLUGIN_NAME }}-${{ env.OD_VERSION }}.zip
      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: kibana-notebooks
          path: ./build
